### ISSUE TITLE
VLCD5 compatibility?

### ISSUE THREAD

**Issue by granis** [wptm/voamca#1]
Seems like a great mod you've done here!
Is it compatible with the vlcd5 display as well?

Also, does this tsdz2-firmware allow control of voltage/amp setting in eeprom?
I am running 52v, and assume you are running 36v only?

(my default tsdz2-firmware didnt allow eeprom setting of 52v, I had to flash another firmware also, found on the endless-sphere thread)

**Comment by wptm** [comment]
Thank you! With vlcd5 I have not tried, but it should work with as well. But the new features will be only accessible with alternative displays which follow the modified UART messages between motor controller and display.

This firmware is different only in 9 bytes (hexadecimal numbers) compared to original. And the purpose of the change is to have voltage, current and pedal cadence sent by motor to display and a firm assist level from display to motor. All the rest are the same like in original. I've uploaded here my modified 36v version. You can follow and do the same changes as I described there on your 52v version. 

I have experience only with my 36v firmware, but I can imagine your issue with your 52v.
